[package]
name = "ublox"
version = "0.2.0"
authors = ["Lane Kolbly <lane@rscheme.org>"]
edition = "2018"
license = "MIT"
description = "A crate to communicate with u-blox GPS devices using the UBX protocol"
repository = "https://github.com/lkolbly/ublox"

[features]
default = []
serial = ["serialport", "crc"]

[dependencies]
chrono = "0.4"
ublox_derive = { path = "../ublox_derive", version = "0.0.1" }
serialport = { version = "3.3.0", optional = true, default-features = false, features = [] }
crc = { version = "1.8.1", optional = true }
bitflags = "1.2.1"

[dev-dependencies]
rand = "0.7.3"
cpu-time = "1.0.0"
